# Generated by Django 3.0.2 on 2020-08-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='gender',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
