# Generated by Django 3.0.2 on 2020-08-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipos de Empleados',
                'db_table': 'Categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='types',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='employe.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='category',
            field=models.ManyToManyField(to='employe.Category'),
        ),
    ]
