# Generated by Django 3.0.2 on 2020-08-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20200816_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo de Empleado'),
        ),
    ]
