# Generated by Django 3.0.2 on 2020-08-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_auto_20200818_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detsale',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalle de Ventas'},
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
