# Generated by Django 3.0.2 on 2020-09-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_auto_20200826_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sexo',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='S/E', max_length=10, verbose_name='Genero'),
        ),
    ]
