# Generated by Django 3.0.2 on 2020-09-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_auto_20200904_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank='S/E', default='S/E', max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
